# Generated by Django 3.0.7 on 2020-06-11 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('matricno', models.CharField(max_length=10, null=True)),
                ('faculty', models.CharField(choices=[('Islamic Studies', 'Islamic Studies'), ('Malay Studies', 'Malay Studies'), ('Cultural', 'Cultural'), ('Dentistry', 'Dentistry'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Science', 'Science'), ('Art & Social Sciences', 'Art & Social Sciences'), ('Business & Accountancy', 'Business & Accountancy'), ('Economics & Administration', 'Economics & Administration'), ('Languages & Linguistics', 'Languages & Linguistics'), ('Built Environment', 'Built Environment'), ('Sports & Exercises Sciences', 'Sports & Exercises Sciences'), ('Computer Science & Information Technology', 'Computer Science & Information Technology')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('Islamic Studies', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Malay Studies', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Cultural', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Dentistry', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Education', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Engineering', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Law', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Medicine', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Science', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Art & Social Sciences', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Business & Accountancy', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Economics & Administration', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Languages & Linguistics', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Built Environment', (('Urban & Regional Planning', 'Urban & Regional Planning'), ('Science Architecture', 'Science Architecture'), ('Quantity Surveying', 'Quantity Surveying'), ('Real Estate', 'Real Estate'), ('Building Surveying', 'Building Surveying'))), ('Sports & Exercises Sciences', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Computer Science & Information Technology', (('Artificial Intelligence', 'Artificial Intelligence'), ('Computer System and Network', 'Computer System and Network'), ('Information Systems', 'Information Systems'), ('Software Engineering', 'Software Engineering'), ('Multimedia', 'Multimedia'), ('Data Science', 'Data Science')))], max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('matricno', models.CharField(max_length=10, null=True)),
                ('faculty', models.CharField(choices=[('Islamic Studies', 'Islamic Studies'), ('Malay Studies', 'Malay Studies'), ('Cultural', 'Cultural'), ('Dentistry', 'Dentistry'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Science', 'Science'), ('Art & Social Sciences', 'Art & Social Sciences'), ('Business & Accountancy', 'Business & Accountancy'), ('Economics & Administration', 'Economics & Administration'), ('Languages & Linguistics', 'Languages & Linguistics'), ('Built Environment', 'Built Environment'), ('Sports & Exercises Sciences', 'Sports & Exercises Sciences'), ('Computer Science & Information Technology', 'Computer Science & Information Technology')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('Islamic Studies', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Malay Studies', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Cultural', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Dentistry', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Education', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Engineering', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Law', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Medicine', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Science', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Art & Social Sciences', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Business & Accountancy', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Economics & Administration', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Languages & Linguistics', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Built Environment', (('Urban & Regional Planning', 'Urban & Regional Planning'), ('Science Architecture', 'Science Architecture'), ('Quantity Surveying', 'Quantity Surveying'), ('Real Estate', 'Real Estate'), ('Building Surveying', 'Building Surveying'))), ('Sports & Exercises Sciences', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('Computer Science & Information Technology', (('Artificial Intelligence', 'Artificial Intelligence'), ('Computer System and Network', 'Computer System and Network'), ('Information Systems', 'Information Systems'), ('Software Engineering', 'Software Engineering'), ('Multimedia', 'Multimedia'), ('Data Science', 'Data Science')))], max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
