# Generated by Django 3.0.7 on 2020-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200612_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
