# Generated by Django 3.0.7 on 2020-06-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200612_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_matched', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('mentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Mentee')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Mentor')),
            ],
        ),
    ]
