# Generated by Django 3.0.7 on 2020-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_matchmentee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchMentee',
        ),
    ]
