# Generated by Django 3.0.7 on 2020-06-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_matchmentee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='cgpa',
            new_name='CGPA',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='cgpa',
            new_name='CGPA',
        ),
    ]
