# Generated by Django 3.0.7 on 2020-06-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200612_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='CGPA',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
