# Generated by Django 3.0.7 on 2020-06-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_mentee_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Mentor'),
        ),
    ]
