# Generated by Django 3.0.7 on 2020-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200612_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='mentor',
        ),
    ]
