# Generated by Django 3.0.7 on 2020-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_mentee_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=200, null=True),
        ),
    ]
