# Generated by Django 3.0.7 on 2020-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_goal_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=200, null=True),
        ),
    ]
