# Generated by Django 3.0.7 on 2020-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20201125_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
