# Generated by Django 3.0.7 on 2020-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20201125_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='setup_date',
            field=models.DateTimeField(help_text='Enter your Name'),
        ),
    ]
