# Generated by Django 3.0.7 on 2020-12-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
