# Generated by Django 3.0.7 on 2020-12-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='profile_pic',
        ),
    ]
