# Generated by Django 3.0.7 on 2020-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_mentor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
