# Generated by Django 3.0.7 on 2020-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_mentor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_pic',
            field=models.ImageField(default='profile1.jpg', null=True, upload_to=''),
        ),
    ]
