# Generated by Django 3.0.7 on 2020-12-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
