# Generated by Django 3.0.7 on 2021-01-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='mentee',
        ),
        migrations.AddField(
            model_name='result',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Match'),
        ),
    ]
