# Generated by Django 3.0.7 on 2021-01-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_answer_category_question_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
    ]
